
project_id = "qascjdhzyipxtqbxcdhg"

[functions.lovable-simplified-direct-subscription]
verify_jwt = false

[functions.lovable-simplified-direct-subscription-test]
verify_jwt = false

[functions.register-webhook]
verify_jwt = true
